---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-pvs-pha
    kind: solution
    catalog_id: 61f11a1f-f54a-45e6-8cba-27c69820db50
    offering_id: e782a64a-33cc-4649-a80d-ec409901fe24
    variations:
      - name: powerha-standard-powervs
        mark_ready: false
        install_type: standard
        import_only: true