name: CI-Pipeline

# Controls when the workflow will run, when comment is created
on:
  issue_comment:
    types:
      - created

env:
  TF_VAR_COS_ACCESS_KEY_ID: ${{ secrets.TF_VAR_COS_ACCESS_KEY_ID }}
  TF_VAR_COS_SECRET_ACCESS_KEY: ${{ secrets.TF_VAR_COS_SECRET_ACCESS_KEY }}

jobs:
  call-terraform-ci-pipeline:
    uses: terraform-ibm-modules/common-pipeline-assets/.github/workflows/common-terraform-module-ci-v2.yml@v1.22.1
    secrets: inherit
    with:
      craSCCv2: true
      craConfigYamlFile: "cra-config.yaml"
